Updated package.json and Added Server.js
ProjectsWithTheBois/SachBoxNew pull request #4
Opened 2021-01-13 23:38 UTC by AndCrit

Added the express dependency into the package.json file. Added the server.js file and initialized with hello world.

2021-01-13 23:40 UTC, bobhare118 commented on my-app/package.json
> +    "express": "^4.17.1",
Green

2021-01-14 00:02 UTC, SachJay commented on my-app/package.json
> +    "express": "^4.17.1",
Red

2021-01-14 00:03 UTC, SachJay requested changes

2021-01-14 00:03 UTC, SachJay commented on my-app/server.js
> +});
NEW LINE ANKIT, THIS IS UNACCEPTABLE

2021-01-14 03:43 UTC, SachJay requested changes

2021-01-14 03:43 UTC, SachJay commented on my-app/package.json
> +    "express": "^4.17.1",
This should be in its own file, currently the frontend and backend are combined but apparently thats not scale able.
I can go fix this.

2021-01-14 03:57 UTC, closed without merging